
FROM node:16.6.2-alpine3.11 AS build-env

USER node

WORKDIR /app

COPY --chown=node package*.json ./

RUN npm install

COPY --chown=node . .

RUN npm run build


FROM nginx:1.21-alpine

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

WORKDIR /usr/share/nginx/html

COPY --from=build-env /app/dist .

ENTRYPOINT ["nginx", "-g", "daemon off;"]