version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: DockerfIle
    restart: always
    depends_on:
      - db
      - backend

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_BASENAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer:standalone
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db  
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: "${DB_BASENAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    command: npm run start
    depends_on:
      - db
      - adminer
  
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: ./nginx
      dockerfile: DockerfIle
    ports:
      - "${HTTP_PORT}:80"
  