version: '3'

services:
  frontend:
    container_name: todolist-frontend
    build:
      context: ./frontend
      dockerfile: DockerfIle-dev
    restart: always
    command: npm run serve
    stdin_open: true
    depends_on:
      - db
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/home/node/app

  db:
    image: woahbase/alpine-mysql:x86_64
    container_name: todolist-mysql
    restart: always
    environment:
      MYSQL_ROOT_PW: root
      MYSQL_USER_DB: todolist
      MYSQL_USER: toor
      MYSQL_USER_PWD: toor
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer:standalone
    container_name: todolist-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db  
  
  backend:
    container_name: todolist-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 4000
      MYSQL_HOST: db
      MYSQL_DATABASE: todolist
      MYSQL_USER: toor
      MYSQL_PASSWORD: toor
    command: npm run dev
    depends_on:
      - db
    volumes:
      - ./backend:/home/node/app
  
  nginx:
    container_name: todolist-nginx
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: ./nginx
      dockerfile: DockerfIle
    ports:
      - "4000:80"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/
  