version: '3'

services:
  frontend:
    container_name: todolist-frontend
    build:
      context: ./frontend
      dockerfile: DockerfIle
    restart: always
    depends_on:
      - db
      - backend

  db:
    image: woahbase/alpine-mysql:x86_64
    container_name: todolist-mysql
    restart: always
    environment:
      MYSQL_ROOT_PW: "${DB_ROOT_PASSWORD}"
      MYSQL_USER_DB: "${DB_BASENAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_USER_PWD: "${DB_PASSWORD}"
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/config:/etc/mysql

  adminer:
    image: adminer:standalone
    container_name: todolist-adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db  
  
  backend:
    container_name: todolist-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: "${DB_BASENAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    command: npm run start
    depends_on:
      - db
      - adminer
  
  nginx:
    container_name: todolist-nginx
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      context: ./nginx
      dockerfile: DockerfIle
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/
  